create table IMAGE(
    id int primary key,
    Body BLOB
);
insert into image (id) values (0);
insert into image values(1, hextoraw('453d7a34'));

SELECT * FROM IMAGE WHERE id = 0; 
CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    USERNAME VARCHAR2(15) UNIQUE,
    PASSWORD VARCHAR2(15),
    EMLOYEE_NAME VARCHAR2(15),
    EMPLOYEE_LASTNAME VARCHAR2(15),
    EMPLOYEE_IS_MANAGER NUMBER (1,0) DEFAULT 0 CHECK (EMPLOYEE_IS_MANAGER = 0 OR EMPLOYEE_IS_MANAGER = 1),
    EMPLOYEE_MANAGER INT,
    EMPLOYEE_EMAIL VARCHAR2(320) CHECK (
    REGEXP_LIKE(EMPLOYEE_EMAIL, '[[:alnum:]]+@[[:alnum:]]+.[[:alnum:]]'))   
);

SELECT * FROM REIMBURSE WHERE EMPLOYEE_ID = 23

INSERT INTO EMPLOYEE (USERNAME, PASSWORD) VALUES ('admin', 'pass');
INSERT INTO EMPLOYEE (USERNAME, PASSWORD, EMLOYEE_NAME,EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL  ) 
VALUES ('ramini', 'pass', 'Ramin', 'I', 'test@gmail.com');

INSERT INTO EMPLOYEE (USERNAME, PASSWORD, EMLOYEE_NAME,EMPLOYEE_LASTNAME, EMPLOYEE_IS_MANAGER, EMPLOYEE_MANAGER, EMPLOYEE_EMAIL  ) 
VALUES ('e1', 'pass', 'emp1', '1', 0, 23, 'test@gmail.com');

INSERT INTO EMPLOYEE (USERNAME, PASSWORD, EMLOYEE_NAME,EMPLOYEE_LASTNAME, EMPLOYEE_IS_MANAGER, EMPLOYEE_MANAGER, EMPLOYEE_EMAIL  ) 
VALUES ('e2', 'pass', 'emp2', '2', 0, 23, 'test2@gmail.com');

SELECT * FROM EMPLOYEE WHERE EMPLOYEE_MANAGER = (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE USERNAME = 'manager')

CREATE Table REIMBURSE(
    REIMBURSE_ID INT PRIMARY KEY,
    REIMBURSE_PROCESS INT,
    EMPLOYEE_ID INT,
    REIMBURSE_TYPE VARCHAR2(15), 
    REIMBURSE_VALUE NUMBER (15,2),
    IMAGE BLOB
);

INSERT INTO REIMBURSE (REIMBURSE_PROCESS, EMPLOYEE_ID, REIMBURSE_TYPE, REIMBURSE_VALUE) VALUES (-1, 22, 'yes', 22.22);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (EMPLOYEE_MANAGER) REFERENCES EMPLOYEE(EMPLOYEE_ID);
/

ALTER TABLE REIMBURSE
ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
/

CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_REIMBURSE_PK
START WITH 1
INCREMENT BY 1;
/

CREATE TRIGGER TR_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE TRIGGER TR_REIMBURE
BEFORE INSERT ON REIMBURSE
FOR EACH ROW
BEGIN
    SELECT SQ_REIMBURSE_PK.NEXTVAL INTO :NEW.REIMBURSE_ID FROM DUAL;
END;
/






