CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    USERNAME VARCHAR2(15) UNIQUE,
    PASSWORD VARCHAR2(15),
    EMLOYEE_NAME VARCHAR2(15),
    EMPLOYEE_LASTNAME VARCHAR2(15),
    EMPLOYEE_IS_MANAGER NUMBER (1,0) DEFAULT 0 CHECK (EMPLOYEE_IS_MANAGER = 0 OR EMPLOYEE_IS_MANAGER = 1),
    EMPLOYEE_MANAGER INT,
    EMPLOYEE_EMAIL VARCHAR2(320) CHECK (
    REGEXP_LIKE(EMPLOYEE_EMAIL, '[[:alnum:]]+@[[:alnum:]]+.[[:alnum:]]'))   
);

INSERT INTO EMPLOYEE (USERNAME, PASSWORD) VALUES ('admin', 'pass');
INSERT INTO EMPLOYEE (USERNAME, PASSWORD, EMLOYEE_NAME,EMPLOYEE_LASTNAME, EMPLOYEE_EMAIL  ) 
VALUES ('admin', 'pass', 'Ramin', 'I', 'test@gmail.com');
CREATE Table REIMBURSE(
    REIMBURSE_ID INT PRIMARY KEY,
    REIMBURSE_PROCESS INT,
    EMPLOYEE_ID INT,
    REIMBURSE_TYPE VARCHAR2(15), 
    REIMBURSE_VALUE NUMBER (15,2)
);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (EMPLOYEE_MANAGER) REFERENCES EMPLOYEE(EMPLOYEE_ID);
/

ALTER TABLE REIMBURSE
ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
/

CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_REIMBURSE_PK
START WITH 1
INCREMENT BY 1;
/

CREATE TRIGGER TR_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE TRIGGER TR_REIMBURE
BEFORE INSERT ON REIMBURSE
FOR EACH ROW
BEGIN
    SELECT SQ_REIMBURSE_PK.NEXTVAL INTO :NEW.REIMBURSE_ID FROM DUAL;
END;
/






